2020-06-23 16:54:00,270 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:47
2020-06-23 16:54:11,529 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:47
2020-06-23 20:49:17,848 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:47
2020-06-23 20:49:53,170 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:47
2020-06-23 20:51:03,401 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:47
2020-06-23 20:51:09,597 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:47
2020-06-23 20:53:02,212 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:47
2020-06-23 21:05:41,245 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:47
2020-06-23 21:06:34,099 ERROR: Exception on /user/yaripey [GET] [in d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py:1891
Traceback (most recent call last):
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\projects\learning\python-flask\app\routes.py", line 86, in user
    return render_template('user.html', user=user, posts=posts)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\projects\learning\python-flask\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\projects\learning\python-flask\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "D:\projects\learning\python-flask\app\templates\user.html", line 16, in block "content"
    {{ form.hidden_tag() }}
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-06-23 21:10:04,793 ERROR: Exception on /user/yaripey [GET] [in d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py:1891
Traceback (most recent call last):
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\projects\learning\python-flask\app\routes.py", line 86, in user
    return render_template('user.html', user=user, posts=posts)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\projects\learning\python-flask\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\projects\learning\python-flask\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "D:\projects\learning\python-flask\app\templates\user.html", line 16, in block "content"
    {{ form.hidden_tag() }}
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-06-23 21:10:40,389 ERROR: Exception on /user/artem [GET] [in d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py:1891
Traceback (most recent call last):
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\projects\learning\python-flask\app\routes.py", line 86, in user
    return render_template('user.html', user=user, posts=posts)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\projects\learning\python-flask\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\projects\learning\python-flask\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "D:\projects\learning\python-flask\app\templates\user.html", line 16, in block "content"
    {{ form.hidden_tag() }}
  File "d:\projects\learning\python-flask\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-06-23 21:11:55,608 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:47
