2020-06-23 21:12:03,768 ERROR: Exception on /follow/artem [POST] [in d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py:1891
Traceback (most recent call last):
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\projects\learning\python-flask\app\routes.py", line 112, in follow
    form = EmtpyForm()
NameError: name 'EmtpyForm' is not defined
2020-06-23 21:13:21,993 ERROR: Exception on /follow/artem [POST] [in d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py:1891
Traceback (most recent call last):
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\projects\learning\python-flask\app\routes.py", line 112, in follow
    form = EmtpyForm()
NameError: name 'EmtpyForm' is not defined
2020-06-23 21:13:51,198 ERROR: Exception on /follow/artem [POST] [in d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py:1891
Traceback (most recent call last):
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\projects\learning\python-flask\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\projects\learning\python-flask\app\routes.py", line 112, in follow
    form = EmtpyForm()
NameError: name 'EmtpyForm' is not defined
2020-06-23 21:14:49,932 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:47
2020-06-23 21:15:35,950 INFO: Microblog startup [in D:\projects\learning\python-flask\app\__init__.py:47
